services:
  web:
    build: ./smileInflatables
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./smileInflatables:/usr/src/smileInflatables
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ryanwanghr
      - POSTGRES_PASSWORD=postgres1!2@3#
      - POSTGRES_DB=smile-inflatables
volumes:
  postgres_data:

