# Generated by Django 5.0.6 on 2024-06-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image_url',
            field=models.FileField(upload_to=''),
        ),
    ]
