# Generated by Django 5.0.6 on 2024-06-13 04:40

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240613_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to=app.models.format_product),
        ),
    ]
