# Generated by Django 5.0.6 on 2024-06-14 03:55

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(max_length=300, upload_to=app.models.format_product),
        ),
    ]
